# Check that the bash script follow a correct style
name: Check bash style

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"


jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Remove folders that do not care about spelling
        run: shellcheck scripts/*.sh
